/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: ['class'],
	content: [
		'./pages/**/*.{ts,tsx}',
		'./components/**/*.{ts,tsx}',
		'./app/**/*.{ts,tsx}',
		'./src/**/*.{ts,tsx}',
	],
	theme: {
		container: {
			center: true,
			padding: '16px',
			screens: {
				sm: '640px',
				md: '768px',
				lg: '1024px',
				xl: '1280px',
			},
		},
		extend: {
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'var(--background)',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'blue-500',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'var(--secondary)',
					foreground: 'var(--secondary-foreground)',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'var(--accent)',
					foreground: 'var(--accent-foreground)',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				bgGrey: 'rgba(0, 0, 0, 0.50)',
			},
			borderRadius: {
				xl: 'calc(var(--radius) + 2px)',
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			keyframes: {
				'accordion-down': {
					from: { height: 0 },
					to: { height: 'var(--radix-accordion-content-height)' },
				},
				'accordion-up': {
					from: { height: 'var(--radix-accordion-content-height)' },
					to: { height: 0 },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
			},
			lineHeight: {
				3: '12px',
				4: '16px',
				5: '20px',
				6: '24px',
				7: '28px',
				8: '32px',
				9: '36px',
				10: '40px',
			},
			gridTemplateColumns: {
				news: 'minmax(100px, 1.2fr), minmax(100px, 0.8fr)',
				about: 'minmax(100px, 1.1fr), minmax(100px, 0.9fr)',
			},
			fontFamily: {
				vinnytsia: ['var(--font-vinnytsia)'],
				sans: ['var(--font-sanomat)'],
			},
		},
		spacing: {
			px: '1px',
			0: '0',
			0.5: '2px',
			1: '4px',
			1.5: '6px',
			2: '8px',
			2.5: '10px',
			3: '12px',
			3.5: '14px',
			4: '16px',
			5: '20px',
			6: '24px',
			7: '28px',
			8: '32px',
			9: '36px',
			10: '40px',
			11: '44px',
			12: '48px',
			14: '56px',
			16: '64px',
			20: '80px',
			24: '96px',
			28: '112px',
			32: '128px',
			36: '144px',
			40: '160px',
			44: '176px',
			48: '192px',
			52: '208px',
			56: '224px',
			60: '240px',
			64: '256px',
			72: '288px',
			80: '320px',
			96: '384px',
		},
		borderRadius: {
			none: '0px',
			sm: '2px',
			DEFAULT: '4px',
			md: '6px',
			lg: '8px',
			xl: '12px',
			'2xl': '16px',
			'3xl': '24px',
			full: '9999px',
		},
		columns: {
			auto: 'auto',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
			8: '8',
			9: '9',
			10: '10',
			11: '11',
			12: '12',
			'3xs': '256px',
			'2xs': '288px',
			xs: '320px',
			sm: '384px',
			md: '448px',
			lg: '512px',
			xl: '576px',
			'2xl': '672px',
			'3xl': '768px',
			'4xl': '896px',
			'5xl': '1024px',
			'6xl': '1152px',
			'7xl': '1280px',
		},
		fontSize: {
			xs: ['12px', { lineHeight: '16px' }],
			sm: ['14px', { lineHeight: '20px' }],
			base: ['16px', { lineHeight: '24px' }],
			lg: ['18px', { lineHeight: '28px' }],
			xl: ['20px', { lineHeight: '28px' }],
			'2xl': ['24px', { lineHeight: '32px' }],
			'3xl': ['30px', { lineHeight: '36px' }],
			'4xl': ['36px', { lineHeight: '36px' }],
			'5xl': ['48px', { lineHeight: '1' }],
			'6xl': ['60px', { lineHeight: '1' }],
			'7xl': ['72px', { lineHeight: '1' }],
			'8xl': ['96px', { lineHeight: '1' }],
			'9xl': ['144px', { lineHeight: '1' }],
		},
		lineHeight: {
			none: '1',
			tight: '1.25',
			snug: '1.375',
			normal: '1.5',
			relaxed: '1.625',
			loose: '2',
			3: '12px',
			4: '16px',
			5: '20px',
			6: '24px',
			7: '28px',
			8: '32px',
			9: '36px',
			10: '40px',
		},
		maxWidth: ({ theme, breakpoints }: any) => ({
			none: 'none',
			0: '0px',
			xs: '320px',
			sm: '384px',
			md: '448px',
			lg: '512px',
			xl: '576px',
			'2xl': '672px',
			'3xl': '768px',
			'4xl': '896px',
			'5xl': '1024px',
			'6xl': '1152px',
			'7xl': '1280px',
			full: '100%',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
			prose: '65ch',
			...breakpoints(theme('screens')),
		}),
	},
	plugins: [require('tailwindcss-animate')],
}
