export { default as Navigation } from '@/components/navigation'
export { default as Hero } from '@/components/hero'
export { default as AboutUs } from '@/components/about-us'
export { default as Partners } from '@components/partners'
export { default as News } from '@components/news'
export { default as Footer } from '@components/footer'
export { default as ScrollUp } from '@components/scroll-up'
export { default as Chakkon } from '@components/chakkon'